### ISSUE TITLE
Media is not showing on android

### ISSUE THREAD

**Issue by Bboy486** [PlayingKarrde/gameOS#185]
Using Skraper.net for assets. 
Note 20 Ultra. Android Up To Date, Pegasus up to date. 
_If no media files are showing up, make sure that Skraper Assets is checked in the Additional Data Sources section of Pegasus settings_
This is enabled. 

 _It may also be preferable to convert the created gamelist.xml (assuming EmulationStation was chosen for the game list in Skraper) to a metadata.txt file using the Pegasus conversion tool_

This was done (attached). 

[metadata.pegasus.txt](https://github.com/PlayingKarrde/gameOS/files/7919929/metadata.pegasus.txt)

**Comment by clintonium-119** [comment]
Mine works on my android FireTV stick.

Looking at your metadata, it may be the path formatting.  Try removing the `./` at the start of your paths.
i.e.
```yaml
game: Fire Emblem: Kakusei
file: ./Fire Emblem - Awakening (Usa)-decrypted.3ds // => change to Fire Emblem - Awakening (Usa)-decrypted.3d
developer: Nintendo
publisher: Intelligent Systems
genre: Strategy-Role playing games
description:
  Fire Emblem Awakening offers a unique blend of in-battle strategy, vast
  character customization, and lush 3D cinematic graphics that appeal to a wide
  range of gamers. In this game, you'll join Chrom, brother to Ylisse's empress
  and commander of its forces, in a fantasy world teetering on the brink of war.
  It's your duty to guide a team of Ylisse's finest soldiers--knights, mages,
  archers, and more--against the marauding Plegian bandits. To succeed, you will
  need to carefully choose the units you take into battle. As you lead your team
  through battles across maps that span entire kingdoms, your army will grow. Some
  characters are willing to join you quickly, while others may need more
  persuasion. Each character earns experience in battle, leveling up and gaining
  strength and abilities as they do so. It's up to you to guide their moves,
  choose their weapons, and direct their attacks.
release: 2013-02-04
players: 2
rating: 90%
x-id: 10996
x-source: ScreenScraper.fr
assets.boxfront: ./media/screenshottitle/Fire Emblem - Awakening (Usa)-decrypted.png // => media/screenshottitle/Fire Emblem - Awakening (Usa)-decrypted.png
```
